### ISSUE TITLE
psycopg2-2.6.2 build failed, but install successeful

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/vanadis#10]
running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-oarq6wlq/psycopg2/setup.py", line 624, in <module>
      ext_modules=ext)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/root/venv/3.5/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError
  
  ----------------------------------------
  Failed building wheel for psycopg2
Failed to build psycopg2
Installing collected packages: psycopg2
  Running setup.py install for psycopg2
Successfully installed psycopg2-2.6.2

**Comment by DronMDF** [comment]
Wheel upgraded and compilation for psycopg2 is not doing. All good.
