### ISSUE TITLE
Docker image segfaulted in project opening

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/vanadis#100]
pygit2.clone_repository or pygit2.Repository is not complete under Django.
Under pure pyhthon git operation are working.

Need to try under Django shell.

**Comment by DronMDF** [comment]
```
    self.repo = pygit2.Repository(str(path))
  File "/usr/lib/python3.5/site-packages/pygit2/repository.py", line 65, in __init__
    super(Repository, self).__init__(path, *args, **kwargs)
KeyError: '/tmp/repos/test'

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7db863e in kill () from /lib/ld-musl-x86_64.so.1
(gdb) bt
#0  0x00007ffff7db863e in kill () from /lib/ld-musl-x86_64.so.1
#1  0x0000000000000000 in ?? ()
(gdb)
```

segfault in musl, this is a libc replacement in alpine... may be alpine is not a good choice?

**Comment by DronMDF** [comment]
alpine:edge is not resolve problem.
